# Generated by Django 2.1.1 on 2018-10-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='posts',
            name='attachment_path',
            field=models.URLField(default='https://google.com'),
        ),
    ]
