version: '3.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mydb101
      POSTGRES_USER: chase
      POSTGRES_DB: 'djangoproject'
    volumes: 
      - .:/docker-entrypoint-initdb.d/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db