# Generated by Django 2.1.2 on 2019-01-12 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeTeam', models.CharField(max_length=40)),
                ('homeTeamScore', models.IntegerField(default=0)),
                ('awayTeam', models.CharField(max_length=40)),
                ('awayTeamScore', models.IntegerField(default=0)),
                ('week', models.IntegerField(default=0)),
                ('eid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Offense_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_eid', models.IntegerField(default=0)),
                ('player_nfl_id', models.CharField(max_length=50)),
                ('pass_attempts', models.IntegerField(default=0)),
                ('pass_completions', models.IntegerField(default=0)),
                ('pass_yards', models.IntegerField(default=0)),
                ('pass_tds', models.IntegerField(default=0)),
                ('pass_ints', models.IntegerField(default=0)),
                ('rush_attempts', models.IntegerField(default=0)),
                ('rush_yards', models.IntegerField(default=0)),
                ('rush_tds', models.IntegerField(default=0)),
                ('longest_rush', models.IntegerField(default=0)),
                ('longest_rush_td', models.IntegerField(default=0)),
                ('receptions', models.IntegerField(default=0)),
                ('rec_yards', models.IntegerField(default=0)),
                ('rec_tds', models.IntegerField(default=0)),
                ('longest_rec', models.IntegerField(default=0)),
                ('longest_rec_td', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('primaryPosition', models.CharField(max_length=200)),
                ('alternatePositions', models.CharField(max_length=200)),
                ('currentTeam', models.CharField(max_length=200)),
                ('shortName', models.CharField(default='J. Doe', max_length=100)),
                ('nfl_id', models.CharField(default='00-000000', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
