# Generated by Django 2.1.1 on 2018-10-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeTeam', models.CharField(max_length=40)),
                ('homeTeamScore', models.IntegerField(default=0)),
                ('awayTeam', models.CharField(max_length=40)),
                ('awayTeamScore', models.IntegerField(default=0)),
            ],
        ),
    ]
