# Generated by Django 2.1.1 on 2018-10-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0004_game_eid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Offense_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_eid', models.IntegerField(default=0)),
                ('player_nfl_id', models.CharField(max_length=50)),
                ('pass_attempts', models.IntegerField(default=0)),
                ('pass_completions', models.IntegerField(default=0)),
                ('pass_yards', models.IntegerField(default=0)),
                ('pass_tds', models.IntegerField(default=0)),
                ('pass_ints', models.IntegerField(default=0)),
                ('rush_attempts', models.IntegerField(default=0)),
                ('rush_yards', models.IntegerField(default=0)),
                ('rush_tds', models.IntegerField(default=0)),
                ('receptions', models.IntegerField(default=0)),
                ('rec_yards', models.IntegerField(default=0)),
                ('rec_tds', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='nfl_id',
            field=models.CharField(default='00-000000', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='shortName',
            field=models.CharField(default='J. Doe', max_length=100),
        ),
    ]
